---
abstract: non-blocking I/O as lambda calculus
author:
  - 'Dmitry Karasik <dmitry@karasik.eu.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Lambda
no_index:
  directory:
    - t
    - inc
requires:
  LWP: 0
  Net::DNS: 0
  Scalar::Util: 0
  Storable: 0
  Sub::Name: 0
  Time::HiRes: 0
  URI: 0
version: 1.23
