# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Lambda
version:      0.16
version_from: lib/IO/Lambda.pm
installdirs:  site
requires:
    LWP:                           0
    Net::DNS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
