--- #YAML:1.0
name:               IO-Lambda
version:            1.21
abstract:           non-blocking I/O as lambda calculus
author:
    - Dmitry Karasik <dmitry@karasik.eu.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:           0
    Net::DNS:      0
    Scalar::Util:  0
    Storable:      0
    Sub::Name:     0
    Time::HiRes:   0
    URI:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
